### ISSUE TITLE
Utilizzo di docker secrets in production.

### ISSUE THREAD

**Issue by n4y0n** [ITISEnricoFermi/archivio-digitale-server#10]
Il problema che pongo è il fatto che al momento passiamo i segreti (jwt secret ecc.) come env nel container del server, cosa poco raccomandabile in quanto rimane nella bash history o nel file ```docker-compose.yml```.

La soluzione che propongo è di utilizzare uno script bash che fa il check delle variabili d'ambiente e se presente una variabile che finisce in VARNAME```_PATH``` setta ```VARNAME```con il valore del secret presente nel path indicato.

Immagino sia questo il metodo utilizzato nei container production ready su dockerhub in quanto viene utilizzata come convenzione... 🐤

**Comment by Richard1984** [comment]
Io volevo anche provare a utilizzare questo modulo qui: [node-convict](https://github.com/mozilla/node-convict).

**Comment by n4y0n** [comment]
> Io volevo anche provare a utilizzare questo modulo qui: [node-convict](https://github.com/mozilla/node-convict).

Figata però rimane il fatto che non supporti i docker secret.
Però una cosa non esclude l'altra anzi è anche meglio se usiamo tutti è due.

**Comment by Richard1984** [comment]
Va benissimo! Io sto facendo un attimo il refactoring di tutto che vorrei anche utilizzare express-validator per il controllo degli input.
