### ISSUE TITLE
Aggiornamento dei container.

### ISSUE THREAD

**Issue by Richard1984** [ITISEnricoFermi/archivio-digitale-server#15]
Implementare la possibilità di aggiornare i container tramite l'Admin Panel.

**Comment by n4y0n** [comment]
Sto pensando a come fare... la soluzione che mi è venuta in mente è quella di fare un servizio updater che magari riceve una richiesta del tipo ``` { "image":"ITISEnricoFermi/archivio-digitale-server", "tag":"0.0.1-alfa" }``` in un endpoint rest
