### ISSUE TITLE
Aumentare limite dimensioni file in upload di Nginx.

### ISSUE THREAD

**Issue by Richard1984** [ITISEnricoFermi/archivio-digitale-server#5]

**Comment by n4y0n** [comment]
E' da fare nel reverse proxy della vps non nel archivio, ho già risolto il problema del archivio.
Aggiungi ```client_max_body_size 0;``` nel context http di nginx sulla vps.
Così le dimensioni massime sono ∞!

**Comment by n4y0n** [comment]
Fatto
